name: Weekly Developer Report

on:
  schedule:
    - cron: '10 10 * * *' # 3:30 PM IST
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Generate Report
        env:
          # This token allows the tool to read the repository data
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm start -- --days=7 --repos="ekalavya-stavir/github-analyzer-demo" --output=report.html
      - name: Check File (Debug)
        run: ls -R # This shows us if report.html was actually created

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ekalavyababu@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Weekly Developer Report
          to: thalapathycaptain15@gmail.com
          from: GitHub Analyzer Automation
          attachments: report.html
